### ISSUE TITLE
keystore error: OS specific error: Cannot open file for writing

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku-compose#32] opened 2023-12-19 12:58 UTC
Running on Ubuntu 22.04.3.

When following the readme instructions, after successfully running `./register-rln.sh` and then running `docker-compose up -d` the following error is triggered:

`ERR 2023-12-18 18:15:24.561+00:00 failed to persist credentials topics="rln_keystore_generator" tid=1 file=rln_keystore_generator.nim:92 error="keystore error: OS specific error: Cannot open file for writing"`

**Comment by Ivansete-status** [comment] 2024-01-02 11:38
I think we need to change the current "write" approach:
https://github.com/waku-org/nwaku/blob/shards-test-dogfooding/waku/waku_keystore/utils.nim#L30-L40

**Comment by gabrielmer** [comment] 2024-01-05 16:33
**Weekly Update**

- _achieved_: attempted many times to reproduce it in VMs. Did not succeed, everything worked.
- _next_: define how to proceed. Either keep attempting to reproduce it, find someone that currently has the issue, or wait for someone to see it again.

**Comment by vpavlin** [comment] 2024-01-08 10:26
@chair28980 Are you running it via Docker Desktop or "native" docker CLI? (IIRC @chaitanyaprem had an issue with volumes using Docker Desktop, not sure if it could be related)

**Comment by chair28980** [comment] 2024-01-08 23:03
> @chair28980 Are you running it via Docker Desktop or "native" docker CLI? (IIRC @chaitanyaprem had an issue with volumes using Docker Desktop, not sure if it could be related)

native docker CLI

**Comment by Ivansete-status** [comment] 2024-01-11 17:31
This seems to be a _Docker_ issue.
I didn't use the `nwaku-compose` for a while and when trying to start the node again I got the following error:

```
nwaku-compose-nwaku-1  | ERR 2024-01-11 17:09:50.063+00:00 4/7 Mounting protocols failed              topics="wakunode main" tid=1 file=wakunode2.nim:89 error="failed to mount waku RLN relay protocol: failed to mount WakuRlnRelay: exception in new WakuRlnRelay: could not parse the keystore: keystore error: OS specific error: Cannot open file for writing"
```
That made the `nwaku` to crash and stop the container.

Thereafter, I added a simple "sleep 1000" so that I can manually enter the docker container and I realised that the `/keystore/keystore.json` was mounted as a folder instead of as file within the container:

![image](https://github.com/waku-org/nwaku-compose/assets/128452529/0b5f3042-13a4-49e5-8eaf-adc1dd6e78ac)

**Comment by chair28980** [comment] 2024-01-12 04:48
This might be due to the erroneous slash at the end of keystore.json here https://github.com/waku-org/nwaku-compose/blob/17444347ba742d2df52863d27c9954dc98bddd2b/docker-compose.yml#L60C24-L60C24

**Comment by gabrielmer** [comment] 2024-01-12 11:45
I've been working the last week on reproducing the original issue without success. Attempted it in Ubuntu, macOs, Windows 10, Windows 11 vm, Windows 10 vm, from WSL, from CMD and probably some other variants. In all cases the keystore generation worked for me without any issues.

On the other hand, two users that had the write problem also had `keystore.json` created as a directory instead of as a file, which should be fixed by this. I'll ask one of them to try again with this new fix.

However, it's very likely that this isn't the root cause of the issue and just a separate bug.

**Comment by gabrielmer** [comment] 2024-01-12 17:40
**Weekly Update**

- _achieved_: more unsuccessful attempts to reproduce it in other environments, talking to users who have the issue to understand further
- _next_: ask users with the issue to run with the new fix, see if it solves the issue either to some, all or none of them. Keep watching and tracking the issue closely

**Comment by chaitanyaprem** [comment] 2024-02-09 07:06
I am running into same issue in one of my nodes on cloud. 
I am using ubuntu 23 and docker CLI to run. 

`ERR 2024-02-09 07:04:37.647+00:00 4/7 Mounting protocols failed              topics="wakunode main" tid=1 file=wakunode2.nim:89 error="failed to mount waku RLN relay protocol: failed to mount WakuRlnRelay: exception in new WakuRlnRelay: could not parse the keystore: keystore error: OS specific error: Cannot open file for writing"`

And i see that keystore.json is created as a directory instead of file. 

```
ls -lrt keystore/
total 4
drwxr-xr-x 2 root root 4096 Feb  9 07:03 keystore.json
```

Do we have a work-around for this?

**Comment by chaitanyaprem** [comment] 2024-02-09 07:17
> I am running into same issue in one of my nodes on cloud. I am using ubuntu 23 and docker CLI to run.
> 
> `ERR 2024-02-09 07:04:37.647+00:00 4/7 Mounting protocols failed topics="wakunode main" tid=1 file=wakunode2.nim:89 error="failed to mount waku RLN relay protocol: failed to mount WakuRlnRelay: exception in new WakuRlnRelay: could not parse the keystore: keystore error: OS specific error: Cannot open file for writing"`
> 
> And i see that keystore.json is created as a directory instead of file.
> 
> ```
> ls -lrt keystore/
> total 4
> drwxr-xr-x 2 root root 4096 Feb  9 07:03 keystore.json
> ```
> 
> Do we have a work-around for this?

Looks like i have figured out the cause for this. 
In my case i did not do rln registration on this node and hence the keystore folder was not present.
When i started nwaku using docker-compose it must have assumed since the path `./keystore/keystore.json` is being mounted and is not available, it must be creating a directory instead of a file. 

The error got fixed after i followed the following steps: 
1. Delete keystore directory
2. Register RLN (which created the keystore dir and keystore.json file within it)
3. Start docker-compose

**Comment by chaitanyaprem** [comment] 2024-02-09 07:43
Maybe https://docs.docker.com/storage/bind-mounts/ can help take care of this situation.

cc @gabrielmer

**Comment by gabrielmer** [comment] 2024-02-13 12:32
Makes sense! Thank you! I'll take a look into this :))

**Comment by gabrielmer** [comment] 2024-02-13 14:27
So found out a couple things:
1- We should mount a volume for `/keystore` instead of `/keystore/keystore.json` as docker automatically creates the paths mounted as directories if they don't exist, as @chaitanyaprem mentioned

2- In nwaku when mounting RLN we try to read the file passed in the `rln-relay-cred-path` flag. This flag has a value by default in nwaku-compose but if the file doesn't exist, we try to open it anyway and get the `OS specific error: Cannot open file for writing` error.
We should also check if the file actually exists before attempting to read from it

Opened PRs for both issues

**Comment by gabrielmer** [comment] 2024-02-15 14:19
Seems to be fixed by https://github.com/waku-org/nwaku-compose/pull/47 :)

**Closed by gabrielmer** 2024-02-15 14:19 UTC
Labels: bug
